export { default as MedicationsTab } from './MedicationsTab'
export { default as NotesTab } from './NotesTab'
export { default as RoutinesTab } from './RoutinesTab'
export { default as RestrictivePracticesTab } from './RestrictivePracticesTab'
export { default as RiskEntriesSection } from './RiskEntriesSection'
export { default as ParticipantConsentsSection } from './ParticipantConsentsSection'
export { default as ContactsTab } from './ContactsTab'
