export { default as MedicationsTab } from './MedicationsTab'
export { default as NotesTab } from './NotesTab'
export { default as RoutinesTab } from './RoutinesTab'
export { default as RestrictivePracticesTab } from './RestrictivePracticesTab'
export { default as RiskEntriesSection } from './RiskEntriesSection'
export { default as ParticipantConsentsSection } from './ParticipantConsentsSection'
export { default as ParticipantHealthConditionsSection } from './ParticipantHealthConditionsSection'
export { default as ParticipantAdlAssessmentsSection } from './ParticipantAdlAssessmentsSection'
export { default as ContactsTab } from './ContactsTab'
export { default as SupportProfileTab } from './SupportProfileTab'
export { default as ClaimsTab } from './ClaimsTab'
export { default as RosteringTab } from './RosteringTab'
export { SectionEditPanel } from './SectionEditPanel'

// PD-7 — Details tab section-edit components, one per SPEC-03 field-group row.
export { default as ParticipantIdentitySection } from './ParticipantIdentitySection'
export { default as ParticipantAddressLivingSection } from './ParticipantAddressLivingSection'
export { default as ParticipantNdisFundingSection } from './ParticipantNdisFundingSection'
export { default as ParticipantKeyIdentifiersSection } from './ParticipantKeyIdentifiersSection'
export { default as ParticipantCulturalBackgroundSection } from './ParticipantCulturalBackgroundSection'
export { default as ParticipantMedicalSection } from './ParticipantMedicalSection'
export { default as ParticipantBehaviourCommunicationSection } from './ParticipantBehaviourCommunicationSection'
export { default as ParticipantCommunityAccessSection } from './ParticipantCommunityAccessSection'
export { default as ParticipantMealsDietSection } from './ParticipantMealsDietSection'
export { default as ParticipantAboutMeSection } from './ParticipantAboutMeSection'
export { default as ParticipantRisksHazardsSummarySection } from './ParticipantRisksHazardsSummarySection'
