using Odip.Api.Services;
using Xunit;

namespace Odip.Tests.Services;

/// <summary>
/// Tests for FirebaseUserService.BuildCreateUserArgs — the one place the Firebase create-user spec is
/// built for every account the app provisions on someone's behalf: an admin creating a user
/// (AdminUsersController.Create) and the first user of a new tenant (TenantsController.CreateWithSetup).
///
/// AuthController.Exchange refuses any token whose email is not verified, and nothing ever sends an
/// app-created user a verification email, so an account created without EmailVerified = true could never
/// sign in. The call that actually creates the account, FirebaseAuth.DefaultInstance.CreateUserAsync, is
/// static and needs a live Firebase connection, so it cannot run offline. The args are therefore built by a
/// public static function and asserted directly — the same approach AuthControllerTests takes for
/// IsEmailVerified.
/// </summary>
public class FirebaseUserServiceTests
{
    // ── Admin Users create: dto.Email, "{FirstName} {LastName}", dto.Password (null unless the admin typed one) ──

    [Fact]
    public void Admin_create_with_a_temporary_password_is_verified_and_keeps_every_other_field()
    {
        var args = FirebaseUserService.BuildCreateUserArgs("new.user@test.example.com", "New User", "P@ssword1");

        Assert.True(args.EmailVerified);
        Assert.Equal("new.user@test.example.com", args.Email);
        Assert.Equal("New User", args.DisplayName);
        Assert.Equal("P@ssword1", args.Password);
        Assert.False(args.Disabled);
        AssertNothingElseIsSet(args);
    }

    [Fact]
    public void Admin_create_without_a_password_is_verified_and_sets_no_password()
    {
        // The new default: the user sets their own password from the emailed link, so none is sent to Firebase.
        var args = FirebaseUserService.BuildCreateUserArgs("new.user@test.example.com", "New User", null);

        Assert.True(args.EmailVerified);
        Assert.Equal("new.user@test.example.com", args.Email);
        Assert.Equal("New User", args.DisplayName);
        Assert.Null(args.Password);
        Assert.False(args.Disabled);
        AssertNothingElseIsSet(args);
    }

    // ── Tenant first user: iu.Email, "{FirstName} {LastName}", iu.Password (optional on CreateInitialUserDto) ──

    [Theory]
    [InlineData("tess.admin@acme.example.com", "Tess Admin", "Sup3r-Secret")]
    [InlineData("tess.admin@acme.example.com", "Tess Admin", null)]
    public void Tenant_first_user_is_verified_and_keeps_every_other_field(string email, string displayName, string? password)
    {
        var args = FirebaseUserService.BuildCreateUserArgs(email, displayName, password);

        Assert.True(args.EmailVerified);
        Assert.Equal(email, args.Email);
        Assert.Equal(displayName, args.DisplayName);
        Assert.Equal(password, args.Password);
        Assert.False(args.Disabled);
        AssertNothingElseIsSet(args);
    }

    // The builder must not start vouching for, or pinning, anything the Firebase project should decide itself:
    // the uid is generated by Firebase, and ODIP holds no phone number or photo for these accounts.
    private static void AssertNothingElseIsSet(FirebaseAdmin.Auth.UserRecordArgs args)
    {
        Assert.Null(args.Uid);
        Assert.Null(args.PhoneNumber);
        Assert.Null(args.PhotoUrl);
    }
}
